SELECT
	dt AS 需求日期,
	purchase_responser AS 采购负责人,
	po_order_code AS 采购订单号,
	aa.sku AS SKU编码,
	aa.sku_cn_name AS SKU名称,
	concat('V', aa.sku_version) as SKU版本号,
	aa.supplier_name AS 供应商,
	deliver_supplier_name AS 发货供应商,
	aa.purchase_subject_name AS 采购组织,
	CASE origin_po_line_est_tr_wh_arrival_date WHEN '1970-01-01' THEN '' ELSE origin_po_line_est_tr_wh_arrival_date END AS 预计到货日期,
	last_po_tracking_content AS 最新跟单备注,
	if(last_po_tracking_time='1970-01-01 08:00:01','',last_po_tracking_time) as 最新跟单时间,
	last_po_tracking_user_name AS 最新跟单人,
	CASE po_line_est_tr_wh_arrival_date WHEN '1970-01-01' THEN '' ELSE po_line_est_tr_wh_arrival_date END AS 人工预计到货日期,
	delivery_gap_days AS 交货期差值,
	delivery_status AS 交货期状态,
	demand_bill_code AS 需求单号,
	purchase_qty AS 采购数量,
	po_line_total_amount as 采购金额,
	po_line_total_amount_with_tax as `采购金额(含税)`,
	aa.purchase_box_qty AS 采购箱数,
	purchase_weight AS `产品总重量(kg)`,
	purchase_volume AS `产品总体积(m3)`,
	received_qty AS 到货数量,
	payment_apply_bill_code_list AS 付款申请单号,
	pay_name AS 付款方式,
	payment_channel_list AS 支付渠道,
	cast(account_period_days as int) AS 账期天数,
	po_delivery_days AS 实际交货时长,
	if(aa.is_first_3_po=1,'是','否') as 是否前三单,
	aa.sku_tag AS 商品标签,
	aa.spec_tags AS 特殊标签,
	if(aa.invoice_flag = 1, '是', '否') as 是否退税,
	ifnull(fs.selection_value, '') as 配送方式,
	demand_source_name AS 需求来源,
	demand_bill_status_name AS 需求状态,
    CASE demand_close_reason_type when '0' then ''
        WHEN '-1' THEN '' WHEN '1' THEN '商品非在售' WHEN '2' THEN '无有效货源' WHEN '3' THEN '达不到最低采购量' WHEN '4' THEN '重新计算补货' END AS 需求关闭原因,
    CASE close_reason_type WHEN '-1' THEN '' WHEN '1' THEN '供应商原因-供应商操作错误关单' WHEN '2' THEN '供应商原因-供应商超10天未发货关单' WHEN '3' THEN '采购操作错误关单' WHEN '4' THEN '采购原因-采购货物异常平账后关单' WHEN '5' THEN '采购原因-采购坏账关单' WHEN '6' THEN '采购原因-采购隔月关单' WHEN '7' THEN '不可控原因-计划部发起退货关单' WHEN '8' THEN '不可控原因-销售停购关单' WHEN '9' THEN '正常关单-完全收货且完全付款自动关单' END AS 订单关闭原因,
    purchase_type_name AS 采购类型,
	CASE po_order_line_status WHEN '10' THEN '待供应商确认' WHEN '20' THEN '待交货' WHEN '30' THEN '供应商拒绝' WHEN '40' THEN '变更审核中' WHEN '50' THEN '交货中' WHEN '60' THEN '交货完成' WHEN '70' THEN '已关闭' END AS 订单行状态,
	CASE DATE(po_create_time) WHEN '1970-01-01' THEN '' ELSE po_create_time END AS 订单生成时间,
	CASE DATE(po_line_confirm_time) WHEN '1970-01-01' THEN '' ELSE po_line_confirm_time END AS 订单确认时间,
	po_confirm_hours AS 订单确认时长,
	receipt_dc_name AS 收货配送中心,
	receipt_warehouse_cn_name AS 收货仓库,
	demand_dc_name AS 需求配送中心,
	demand_warehouse_cn_name AS 需求仓库,
	asn_code_list AS ASN单号,
	CASE po_line_last_sign_date WHEN '1970-01-01' THEN '' ELSE po_line_last_sign_date END AS 中仓签收时间,
	CASE po_line_last_received_date WHEN '1970-01-01' THEN '' ELSE po_line_last_received_date END AS 中仓收货时间,
	unqualified_qty AS 不合格数量,
	wh_rejected_qty AS 拒收数量,
	shelved_qty AS 上架数量,
	purchase_return_order_code_list AS 采购退货单号,
	expect_return_qty AS 计划退货数量,
	actual_return_qty AS 实际退货出库数量,
	supplier_manager AS 商户负责人,
	aa.sale_department AS 末级部门
FROM
	ads.ads_pad_purchase_excute_details_df as aa
left join (select * from dwd.dwd_dim_dashboard_filter_selection_nf where filter_key = 25) fs on fs.selection_key = aa.pickup_method
    where aa.po_order_date >= '2026-01-01'
    ;